### ISSUE TITLE
sbt-spark-package;0.2.4: not found

### ISSUE THREAD

**Issue by jocerfranquiz** [radanalyticsio/streaming-amqp#20]
Hi,

I'm was running `sbt assembly` on this project but I got this error:

`sbt.ResolveException: unresolved dependency: org.spark-packages#sbt-spark-package;0.2.4: not found`

Thanks :+1:

**Comment by ppatierno** [comment]
The SBT tool for building isn't supported anymore after moving to Maven. I forgot to delete it. Now I removed it from the repo. Please use Maven for building.
