### ISSUE TITLE
--packages install cannot resolve dependencies

### ISSUE THREAD

**Issue by ducktrA** [radanalyticsio/streaming-amqp#21]
Hi,

i struggle with packages install. Happy to support in terms of documentation if i get it running.

bin/spark-shell --packages org.apache.spark:spark-streaming-amqp_2.11:0.1.0

says that it cannot find the package:

==== spark-packages: tried

	  http://dl.bintray.com/spark-packages/maven/org/apache/spark/spark-streaming-amqp_2.11/0.1.0/spark-streaming-amqp_2.11-0.1.0.pom

	  -- artifact org.apache.spark#spark-streaming-amqp_2.11;0.1.0!spark-streaming-amqp_2.11.jar:

	  http://dl.bintray.com/spark-packages/maven/org/apache/spark/spark-streaming-amqp_2.11/0.1.0/spark-streaming-amqp_2.11-0.1.0.jar

		::::::::::::::::::::::::::::::::::::::::::::::

		::          UNRESOLVED DEPENDENCIES         ::

		::::::::::::::::::::::::::::::::::::::::::::::

		:: org.apache.spark#spark-streaming-amqp_2.11;0.1.0: not found

		::::::::::::::::::::::::::::::::::::::::::::::

Thanks in advance

**Comment by ppatierno** [comment]
Hi,

as the landing page says "the library needs to be installed into the local repository.". Did you execute a "mvn clean install" command from the root project directory (where the pom.xml file is located) ?

**Comment by ducktrA** [comment]
Paolo,

not familiar with mvn and couldnt translate "getting it in local
repository" to mvn clean install properly. I am doing it right now and
after downloading the half world it finished with Success.

It is found now. Thanks for your quick response and the lib.

2016-12-02 10:57 GMT+01:00 Paolo Patierno <notifications@github.com>:

**Comment by ppatierno** [comment]
You are very welcome ! I'll add something more explicit about installing the package in the local repository, thanks for the feedback ! ;)
