### ISSUE TITLE
Python example with RabbitMQ

### ISSUE THREAD

**Issue by Co0key** [radanalyticsio/streaming-amqp#22]
Hi, 
I have some problems with the python example. I compiled the project and start the script by adding the jar file as parameter. The application is running, but I see no connection on my overview.
The first question, is it possible to connect to RabbitMQ?

Thanks in advance

**Comment by ppatierno** [comment]
Hi,
RabbitMQ supports not standard AMQP 0.9 version. The Spark Streaming connector is for AMQP 1.0 standard protocol version.
