### ISSUE TITLE
Should these artifacts be in the "org.apache.spark" group/organization?

### ISSUE THREAD

**Issue by erikerlandson** [radanalyticsio/streaming-amqp#23]
As in:

![image](https://user-images.githubusercontent.com/259898/28093005-60b21caa-664a-11e7-86ee-00aaa505314d.png)

I was under the impression that only apache spark artifacts were supposed to use that group name

**Comment by Jiri-Kremser** [comment]
imho, we shouldn't use the `org.apache.spark` groupId. This way we are not able to publish them to mvn sonatype/central and other our projects that depend on this library would keep failing to compile without installing this into local maven repo.

I can create an issue on issues.sonatype.org that we want to be able to publish under `io.radanalytics.*` if no one has done that before... I recall some discussion about it on Slack couple of months ago.

**Comment by Jiri-Kremser** [comment]
@elmiko what do you think about ^ ? I've just hit related issue when doing this tutorial https://radanalytics.io/examples/amqpstreaming. The page with tutorial says that user should build the repo as described [here](https://github.com/redhat-iot/amqp-spark-demo#building-the-demo-source-code), but the `demo/amqp-spark-driver/` depends on `org.apache.spark:spark-streaming-amqp_2.11:jar:0.1.0`, but the current version is `0.2.0`.

Well, the versioning of this repo is another issue, it's hard to say what commit corresponds to `0.1.0`, imho it would be better to use the `-SNAPSHOT` and the maven release plugin.

**Comment by erikerlandson** [comment]
I still think this should be outside of `org.apache.spark` - releases should each be tagged in GH as well as part of standard release process, and the tip of develop/master should be in "<next>-SNAPSHOT"

**Comment by elmiko** [comment]
i have to admit a little ignorance about how sonatype records these namespaces, but in general if we can't use the official org.apache.spark namespace then i think we should definitely try to utilize io.radanalytics.*

**Comment by erikerlandson** [comment]
We can run it by @mattf and @willb to confirm, but I think we should start the process of registering `io.radanalytics` via sonatype
