### ISSUE TITLE
Spark streaming  from RabbitMQ using AMQP 

### ISSUE THREAD

**Issue by karyampudi** [radanalyticsio/streaming-amqp#33]
Hi,

 I am trying to fetching data from RabbitMQ using spark streaming with AMQP utility. I am not able to get any data. 
please find below code and help me on the same.

JavaSparkContext javaSparkContext = new JavaSparkContext(sparkSession.sparkContext());
        JavaStreamingContext javaStreamingContext = new JavaStreamingContext(javaSparkContext, Durations.seconds(Long.parseLong(sparkStreamingInterval)));
        javaStreamingContext.checkpoint(sparkCheckpointDir);

               
        Function<org.apache.qpid.proton.message.Message,scala.Option<java.lang.String>> messageHandler1 = new Function<org.apache.qpid.proton.message.Message, scala.Option<java.lang.String>>() {

            public Option<String> call(Message message) {

                return new Some(message.getBody());
        };

      

        JavaReceiverInputDStream<String>  receiveStream =
                AMQPUtils.createStream(javaStreamingContext,"localhost",
                        5672,
                        Option.apply("guest"),
                        Option.apply("guest"),
                        "test", messageHandler1, StorageLevel.MEMORY_AND_DISK());

       
        receiveStream.foreachRDD(rdd->{
            System.out.println("count"+rdd.count());
        });

test--  queue name of RabbitMQ

**Comment by ppatierno** [comment]
Hi,
this connector is for AMQP 1.0. RabbitMQ has the AMQP 0.9.1 protocol which is completely different.

**Comment by karyampudi** [comment]
<groupId>io.radanalytics</groupId>
			<artifactId>spark-streaming-amqp_2.11</artifactId>
			<version>0.3.0</version>
I am using above jar. Let me know is it possible streaming RabbitMQ using AMQP.createStream

**Comment by karyampudi** [comment]
ppatierno

please help me on the same. I am using RabbitMQ + Spark Streaming +AMQP

**Comment by ppatierno** [comment]
I'm talking about the AMQP protocol version not jars.
This connector is for AMQP 1.0 (OASIS and ISO/IEC standard) not for the AMQP 0.9.1 version.
They have same name (AMQP) but they are two different protocols.
You cannot use this connector with RabbitMQ.

**Comment by karyampudi** [comment]
Thank you for your information. Right now I am using RabbitMQUtils.createJavaDistributedStream to fetch content from RabbitMQ using SparkStreaming.
Let me know what are the other ways for RabbitMQ + spark Streaming.  It will great helpful to me.

**Comment by ppatierno** [comment]
I'm not using RabbitMQ so I cannot be helpful on this sorry.
